# Generated by Django 3.1.1 on 2020-09-26 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=64)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=99)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Income_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=64)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=99)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget')),
            ],
            options={
                'verbose_name_plural': 'Income Categories',
            },
        ),
        migrations.CreateModel(
            name='Income_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=99)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget')),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.income_category')),
            ],
            options={
                'verbose_name_plural': 'Income Items',
            },
        ),
        migrations.CreateModel(
            name='Expense_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=99)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.expense_category')),
            ],
            options={
                'verbose_name_plural': 'Expense Items',
            },
        ),
    ]
