# Generated by Django 3.1.1 on 2020-09-26 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
