# Generated by Django 3.1.1 on 2020-09-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20200926_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget'},
        ),
        migrations.AlterModelOptions(
            name='expense_category',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense_item',
            options={'verbose_name': 'Expense Item', 'verbose_name_plural': 'Expense Items'},
        ),
        migrations.AlterModelOptions(
            name='income_category',
            options={'verbose_name': 'Income Category', 'verbose_name_plural': 'Income Categories'},
        ),
        migrations.AlterModelOptions(
            name='income_item',
            options={'verbose_name': 'Income Item', 'verbose_name_plural': 'Income Items'},
        ),
        migrations.AlterField(
            model_name='expense_category',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='expense_item',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='income_category',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='income_item',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
