# Generated by Django 3.1.1 on 2020-09-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20200926_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense_category',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
    ]
