# Generated by Django 3.1.1 on 2020-09-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20200926_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense_category',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
    ]
