# Generated by Django 3.1.1 on 2020-09-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_budget_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_item',
            name='description',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.expense_category'), max_length=32),
        ),
        migrations.AlterField(
            model_name='income_item',
            name='description',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.income_category'), max_length=32),
        ),
    ]
