# Generated by Django 3.1.1 on 2020-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_auto_20200929_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_item',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='income_item',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
